# Generated by Django 5.1 on 2024-10-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер столика')),
                ('seats', models.IntegerField(verbose_name='Количество мест')),
            ],
            options={
                'verbose_name': 'Столик',
                'verbose_name_plural': 'Столики',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TimeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_section', models.CharField(verbose_name='час')),
            ],
            options={
                'verbose_name': 'Часовая секция',
                'verbose_name_plural': 'Часовые секции',
                'ordering': ['time_section'],
            },
        ),
    ]
