# Generated by Django 4.2 on 2024-11-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_confirm',
            field=models.BooleanField(default=False, verbose_name='Поле подтверждения бронирования'),
        ),
    ]
